services:
  - type: web
    name: kri8tivemerch
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run preview -- --port $PORT --host 0.0.0.0
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_APPWRITE_ENDPOINT
        sync: false
      - key: VITE_APPWRITE_PROJECT_ID
        sync: false
      - key: VITE_PAYSTACK_PUBLIC_KEY
        sync: false
      - key: VITE_IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: VITE_IMAGEKIT_URL_ENDPOINT
        sync: false
      - key: VITE_IMAGEKIT_PRIVATE_KEY
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 