/**
 * Permission System Constants
 * Defines all permissions, resources, and role-based access control
 */

// Permission Types
export const PERMISSION_TYPES = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  MANAGE: 'manage' // Full CRUD permissions
} as const;

// Resource Types
export const RESOURCE_TYPES = {
  PRODUCTS: 'products',
  ORDERS: 'orders',
  USERS: 'users',
  ANALYTICS: 'analytics',
  CATEGORIES: 'categories',
  REVIEWS: 'reviews',
  COUPONS: 'coupons',
  SHIPPING: 'shipping',
  CUSTOMIZATIONS: 'customizations',
  SYSTEM: 'system'
} as const;

// Role Types
export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  SHOP_MANAGER: 'shop_manager',
  CUSTOMER: 'user'
} as const;

// Permission Levels
export const PERMISSION_LEVELS = {
  NONE: 'none',
  READ: 'read',
  LIMITED: 'limited',
  MANAGE: 'manage',
  FULL: 'full'
} as const;

// Default Role Permissions
export const DEFAULT_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: {
    [RESOURCE_TYPES.PRODUCTS]: PERMISSION_LEVELS.FULL,
    [RESOURCE_TYPES.ORDERS]: PERMISSION_LEVELS.FULL,
    [RESOURCE_TYPES.USERS]: PERMISSION_LEVELS.FULL,
    [RESOURCE_TYPES.ANALYTICS]: PERMISSION_LEVELS.FULL,
    [RESOURCE_TYPES.CATEGORIES]: PERMISSION_LEVELS.FULL,
    [RESOURCE_TYPES.REVIEWS]: PERMISSION_LEVELS.FULL,
    [RESOURCE_TYPES.COUPONS]: PERMISSION_LEVELS.FULL,
    [RESOURCE_TYPES.SHIPPING]: PERMISSION_LEVELS.FULL,
    [RESOURCE_TYPES.CUSTOMIZATIONS]: PERMISSION_LEVELS.FULL,
    [RESOURCE_TYPES.SYSTEM]: PERMISSION_LEVELS.FULL
  },
  [ROLES.SHOP_MANAGER]: {
    [RESOURCE_TYPES.PRODUCTS]: PERMISSION_LEVELS.MANAGE,
    [RESOURCE_TYPES.ORDERS]: PERMISSION_LEVELS.MANAGE,
    [RESOURCE_TYPES.USERS]: PERMISSION_LEVELS.LIMITED,
    [RESOURCE_TYPES.ANALYTICS]: PERMISSION_LEVELS.READ,
    [RESOURCE_TYPES.CATEGORIES]: PERMISSION_LEVELS.MANAGE,
    [RESOURCE_TYPES.REVIEWS]: PERMISSION_LEVELS.MANAGE,
    [RESOURCE_TYPES.COUPONS]: PERMISSION_LEVELS.MANAGE,
    [RESOURCE_TYPES.SHIPPING]: PERMISSION_LEVELS.MANAGE,
    [RESOURCE_TYPES.CUSTOMIZATIONS]: PERMISSION_LEVELS.MANAGE,
    [RESOURCE_TYPES.SYSTEM]: PERMISSION_LEVELS.NONE
  },
  [ROLES.CUSTOMER]: {
    [RESOURCE_TYPES.PRODUCTS]: PERMISSION_LEVELS.READ,
    [RESOURCE_TYPES.ORDERS]: PERMISSION_LEVELS.LIMITED, // Own orders only
    [RESOURCE_TYPES.USERS]: PERMISSION_LEVELS.LIMITED, // Own profile only
    [RESOURCE_TYPES.ANALYTICS]: PERMISSION_LEVELS.NONE,
    [RESOURCE_TYPES.CATEGORIES]: PERMISSION_LEVELS.READ,
    [RESOURCE_TYPES.REVIEWS]: PERMISSION_LEVELS.LIMITED, // Own reviews + read all
    [RESOURCE_TYPES.COUPONS]: PERMISSION_LEVELS.READ,
    [RESOURCE_TYPES.SHIPPING]: PERMISSION_LEVELS.READ,
    [RESOURCE_TYPES.CUSTOMIZATIONS]: PERMISSION_LEVELS.LIMITED, // Own requests only
    [RESOURCE_TYPES.SYSTEM]: PERMISSION_LEVELS.NONE
  }
} as const;

// Detailed Action Permissions
export const ACTION_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: {
    [RESOURCE_TYPES.PRODUCTS]: [
      PERMISSION_TYPES.CREATE,
      PERMISSION_TYPES.READ,
      PERMISSION_TYPES.UPDATE,
      PERMISSION_TYPES.DELETE,
      PERMISSION_TYPES.MANAGE
    ],
    [RESOURCE_TYPES.ORDERS]: [
      PERMISSION_TYPES.CREATE,
      PERMISSION_TYPES.READ,
      PERMISSION_TYPES.UPDATE,
      PERMISSION_TYPES.DELETE,
      PERMISSION_TYPES.MANAGE
    ],
    [RESOURCE_TYPES.USERS]: [
      PERMISSION_TYPES.CREATE,
      PERMISSION_TYPES.READ,
      PERMISSION_TYPES.UPDATE,
      PERMISSION_TYPES.DELETE,
      PERMISSION_TYPES.MANAGE
    ],
    [RESOURCE_TYPES.ANALYTICS]: [
      PERMISSION_TYPES.READ,
      PERMISSION_TYPES.MANAGE
    ],
    [RESOURCE_TYPES.SYSTEM]: [
      PERMISSION_TYPES.MANAGE
    ]
  },
  [ROLES.SHOP_MANAGER]: {
    [RESOURCE_TYPES.PRODUCTS]: [
      PERMISSION_TYPES.CREATE,
      PERMISSION_TYPES.READ,
      PERMISSION_TYPES.UPDATE,
      PERMISSION_TYPES.DELETE
    ],
    [RESOURCE_TYPES.ORDERS]: [
      PERMISSION_TYPES.READ,
      PERMISSION_TYPES.UPDATE
    ],
    [RESOURCE_TYPES.USERS]: [
      PERMISSION_TYPES.READ
    ],
    [RESOURCE_TYPES.ANALYTICS]: [
      PERMISSION_TYPES.READ
    ]
  },
  [ROLES.CUSTOMER]: {
    [RESOURCE_TYPES.PRODUCTS]: [
      PERMISSION_TYPES.READ
    ],
    [RESOURCE_TYPES.ORDERS]: [
      PERMISSION_TYPES.CREATE,
      PERMISSION_TYPES.READ // Own orders only
    ],
    [RESOURCE_TYPES.USERS]: [
      PERMISSION_TYPES.READ,
      PERMISSION_TYPES.UPDATE // Own profile only
    ],
    [RESOURCE_TYPES.REVIEWS]: [
      PERMISSION_TYPES.CREATE,
      PERMISSION_TYPES.READ,
      PERMISSION_TYPES.UPDATE // Own reviews only
    ]
  }
} as const;

// Permission Labels for UI
export const PERMISSION_LABELS = {
  [PERMISSION_LEVELS.NONE]: 'No Access',
  [PERMISSION_LEVELS.READ]: 'View Only',
  [PERMISSION_LEVELS.LIMITED]: 'Limited Access',
  [PERMISSION_LEVELS.MANAGE]: 'Manage',
  [PERMISSION_LEVELS.FULL]: 'Full Control'
} as const;

// Resource Labels for UI
export const RESOURCE_LABELS = {
  [RESOURCE_TYPES.PRODUCTS]: 'Products',
  [RESOURCE_TYPES.ORDERS]: 'Orders',
  [RESOURCE_TYPES.USERS]: 'Users',
  [RESOURCE_TYPES.ANALYTICS]: 'Analytics',
  [RESOURCE_TYPES.CATEGORIES]: 'Categories',
  [RESOURCE_TYPES.REVIEWS]: 'Reviews',
  [RESOURCE_TYPES.COUPONS]: 'Coupons',
  [RESOURCE_TYPES.SHIPPING]: 'Shipping',
  [RESOURCE_TYPES.CUSTOMIZATIONS]: 'Customizations',
  [RESOURCE_TYPES.SYSTEM]: 'System Settings'
} as const;

// Role Labels for UI
export const ROLE_LABELS = {
  [ROLES.SUPER_ADMIN]: 'Super Admin',
  [ROLES.SHOP_MANAGER]: 'Shop Manager',
  [ROLES.CUSTOMER]: 'Customer'
} as const;

// Type exports
export type PermissionType = typeof PERMISSION_TYPES[keyof typeof PERMISSION_TYPES];
export type ResourceType = typeof RESOURCE_TYPES[keyof typeof RESOURCE_TYPES];
export type RoleType = typeof ROLES[keyof typeof ROLES];
export type PermissionLevel = typeof PERMISSION_LEVELS[keyof typeof PERMISSION_LEVELS]; 